POST http://localhost:3001/api/collection
Content-Type: application/json

{
	"username": "623a1fed734652a9bc9ec0e3",
	"owned": [{
		"name": "6234fdfbb988d590169ccea3",
		"gameStats": {
			"plays": 26,
			"wins": 21
		},
		"rating": 5,
		"active": true
	}]
}